name: Sync Template on Template Release

on:
  repository_dispatch:
    types: [template-release] # Triggered remotely from template repo
  workflow_dispatch:

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - name: Determine target branch
        id: branch-check
        run: |
          if git ls-remote --heads origin dev | grep dev; then
            echo "branch=dev" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.branch-check.outputs.branch }}

      - name: Configure Git
        run: |
          git config --global user.name "Terrabyte Bot"
          git config --global user.email "bot@terrabyte.tech"

      - name: Pull latest template release
        run: |
          git subtree pull \
            --prefix=template \
            https://github.com/terrabyte-tech/terrabyte-11ty-template.git \
            ${{ github.event.client_payload.tag }} \
            --squash

      - name: Commit & Push changes
        run: |
          git add template
          git commit -m "chore: sync template to release ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.commit_message_suffix }}" || echo "No changes to commit"
          git push origin ${{ steps.branch-check.outputs.branch }}
